### PR TITLE
feat: add model validation and add missing relations modifiers

### PR DESCRIPTION
**Pull request by bacali95**

### CODE REVIEW

**Comment by bacali95** [comment]
Friendly ping @cwqt

**Comment by cwqt** [comment]
hey sorry, busy with work & life... nice work though! could you add an example of using `RelationName` in the `schema.ts` under `__tests__` - I need to write some more test cases / update documentation to go with these changes before releasing

**Comment by cwqt** [comment]
Also playing around with stricter types for relations rather than just a spread of modifiers, since you could supply `Fields` but not `References` as currently is:

```ts
export const OneToOne = <
  T extends 'OneToOne',
  M extends Types.Blocks.Model,
  K extends Types.Modifiers<T>,
>(
  model: M | string,
  ...modifiers:
    | [
        Types.Modifier<'OneToOne', 'fields'>,
        Types.Modifier<'OneToOne', 'references'>,
        ...Types.Modifier<T, Exclude<K, 'fields' | 'references'>>[],
      ]
    | Types.Modifier<T, Exclude<K, 'fields' | 'references'>>[]
): Types.Fields.Field<T, K> => ({
  type: 'OneToOne' as const as T,
  modifiers: [
    {
      type: 'model' as const,
      value: model,
    },
    ...modifiers,
  ].filter(nonNullable) as Types.Modifier<T, K>[],
});


let a = OneToOne(Post, Fields('bestPostId'), References('id')); // good
let b = OneToOne(Post, References('id'), Fields('bestPostId')); // bad
let c = OneToOne(Post, Fields('bestPostId')); // bad
let d = OneToOne(Post); // good
```

I'll try and find some time tomorrow night to finish this

**Comment by bacali95** [comment]
Hey @cwqt, I just added an example for `RelationName` modifier, I just hope the field's names are correct, I'm not that good with naming stuff :sweat_smile: 
Your changes look more reasonable, can't wait to read your changes :smile:

**Comment by cwqt** [comment]
Got around to polishing this off, did a couple changes namely removing `RelationName` in favour of some arcane types:

```ts
m.Relation('pinnedBy', OneToOne(User, "PinnedPost", Fields('pinnedById'), References('id'), Nullable))
//  pinnedBy   User?   @relation("PinnedPost", fields: [pinnedById], references: [id])

m.Relation('pinnedBy', OneToOne(User, Fields('pinnedById'), References('id'), Nullable))
//  pinnedBy   User?   @relation(fields: [pinnedById], references: [id])
```

Which is a bit terser & follows closer to the Prisma schema... there's also some constraints on the ordering of name, fields & references (from previous comment). I haven't tested it super thoroughly, so please give it a try and let me know if something isn't working correctly :)

**Comment by bacali95** [comment]
I will start adding some validating tests

**Comment by cwqt** [comment]
Thanks again for your contribution, great work :) I think now with your help this package has reached parity with the Prisma schema?
& these changes are live now at v1.1.0

**Comment by bacali95** [comment]
> Thanks again for your contribution, great work :) I think now with your help this package has reached parity with the Prisma schema? & these changes are live now at v1.1.0

Always happy to contribute :sweat_smile: Yes I think this library can generate any schema case possible, I will keep using it until I find anything missing ;)

**Pull request merged**
